### ISSUE TITLE
transparent not working in vscode terminal

### ISSUE THREAD

**Issue by floh96** [JanDeDobbeleer/oh-my-posh3#182]
### Prerequisites

- [x ] I have read and understand the `CONTRIBUTING` guide
- [x ] I looked for duplicate issues before submitting this one

### Description

the transparent effekt is not working in the vscode terminal. It is displaying black background see screenshoots.

### Environment

- Oh my Posh version: 3.44.1-beta
- Theme: fish with some [changes](https://gist.github.com/floh96/1f26bff98d6b87255146b98f148860ff)
- Operating System: windows 10
- Shell: powershell version 7.1.0
- Terminal: vscode integrated terminal

### Steps to Reproduce

open vscode integrated terminal

**Expected behavior:**

transparent effekt displays korrekt like in windows terminal 
![terminal](https://user-images.githubusercontent.com/49693964/99911635-1cb2f800-2cf6-11eb-8f14-76b308127d09.PNG)

**Actual behavior:**

transparent effekt displays not korrekt (black)
![vscode](https://user-images.githubusercontent.com/49693964/99911527-5fc09b80-2cf5-11eb-92da-fef9b1ce4e38.PNG)

**Comment by JanDeDobbeleer** [comment]
That's a bug in VSCode not handling the inverted ANSI correctly. Can you open an issue there?

**Comment by floh96** [comment]
@JanDeDobbeleer sorry to bother you could you open the issue you could it exlain better i think :)

**Comment by JanDeDobbeleer** [comment]
That's a good idea. I'll do it tomorrow with a proper sample they can use to reproduce this.
